import existingWorker from "./index.js";
import { verifySessionToken } from "./auth.js";

const SERVICES = [
  "Networking", "Live session", "Lectures", "Guest appearance", "Web development",
  "Self-development coaching", "Career path guidance", "Resume / CV review",
  "Interview preparation", "Network troubleshooting consultation", "Technical mentoring",
  "Workshop / training",
];
const ONLINE_WINDOW_MS = 45 * 1000;
const CONNECT_WINDOW_MS = 3 * 60 * 1000;
const VERIFICATION_TTL_MS = 10 * 60 * 1000;
const EXPLICIT_RE = /\b(sex|sexual|nude|nudity|naked|porn|xxx|nsfw|boobs|breasts|dick|penis|vagina|blowjob|masturbat|erotic|onlyfans)\b/i;

function corsHeaders(request) { const origin=request.headers.get("Origin"); const allowed=["https://naveenshankar.in","https://www.naveenshankar.in","https://admin.naveenshankar.in"]; return {"Access-Control-Allow-Origin":allowed.includes(origin)?origin:allowed[0],"Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Sana-Session,X-Sana-Timezone","Access-Control-Allow-Credentials":"true",Vary:"Origin"}; }
function json(request,data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...corsHeaders(request)}});}
function now(){return Date.now();}
function timezoneFromRequest(request){return request.headers.get("X-Sana-Timezone")||"Asia/Kolkata";}
function partsForTimezone(timeZone,date=new Date()){try{const text=new Intl.DateTimeFormat("en-US",{timeZone,weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).format(date);const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone,hour:"numeric",hour12:false}).format(date));return{text,hour};}catch{return partsForTimezone("Asia/Kolkata",date);}}
function dayGreeting(hour){return hour>=5&&hour<12?"Good morning":hour>=12&&hour<17?"Good afternoon":hour>=17&&hour<21?"Good evening":"Hi";}
function timeToMinutes(v){if(!v)return null;const m=String(v).match(/(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(!m)return null;let h=Number(m[1]);const min=Number(m[2]||0);const ap=(m[3]||"").toLowerCase();if(ap==="pm"&&h<12)h+=12;if(ap==="am"&&h===12)h=0;return h*60+min;}
function getISTParts(date=new Date()){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(date);const g=t=>p.find(x=>x.type===t)?.value;return{dateStr:`${g("year")}-${g("month")}-${g("day")}`,minutesOfDay:Number(g("hour"))*60+Number(g("minute"))};}
async function sha256(value){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function sessionId(request){const supplied=request.headers.get("X-Sana-Session");if(supplied&&/^[a-zA-Z0-9_-]{12,100}$/.test(supplied))return supplied;return(await sha256(`${request.headers.get("CF-Connecting-IP")||"unknown"}:${request.headers.get("User-Agent")||"unknown"}`)).slice(0,40);}
async function ensureSession(env,request){const id=await sessionId(request);const timezone=timezoneFromRequest(request);const country=request.headers.get("CF-IPCountry")||"";await env.DB.prepare(`INSERT INTO sana_sessions(id,timezone,country,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET timezone=excluded.timezone,country=excluded.country,updated_at=excluded.updated_at`).bind(id,timezone,country,now(),now()).run();return id;}
function cleanAiText(r){return(r?.response||r?.output_text||(Array.isArray(r?.output)&&r.output.find(o=>o.content)?.content?.[0]?.text)||"").trim();}
async function adminAuth(request,env){const a=request.headers.get("Authorization")||"";const t=a.startsWith("Bearer ")?a.slice(7):null;return t?verifySessionToken(env.SESSION_SECRET,t):null;}
async function saveMessage(env,session,conversationId,sender,message){await env.DB.prepare("INSERT INTO sana_messages(session_id,conversation_id,sender,message,created_at) VALUES(?,?,?,?,?)").bind(session,conversationId||null,sender,message,now()).run();}

async function getAvailabilityStatus(env){const{dateStr:today,minutesOfDay}=getISTParts();const yesterday=new Date(Date.now()-86400000);const{dateStr:yesterdayStr}=getISTParts(yesterday);const[a,b,shifts]=await Promise.all([env.DB.prepare("SELECT shift_type FROM availability WHERE date=?").bind(today).first(),env.DB.prepare("SELECT shift_type FROM availability WHERE date=?").bind(yesterdayStr).first(),env.DB.prepare("SELECT * FROM shift_types").all()]);const map={};(shifts.results||[]).forEach(s=>map[s.code]=s);const evalShift=e=>{if(!e)return null;const s=map[e.shift_type];if(!s||s.is_off)return{available:false,shift:s};const start=timeToMinutes(s.start_time),end=timeToMinutes(s.end_time);const within=s.end_next_day?minutesOfDay>=start||minutesOfDay<end:minutesOfDay>=start&&minutesOfDay<end;return{available:within,shift:s};};const x=evalShift(a),y=evalShift(b);if(x?.available)return{available:true,shift:x.shift};if(y?.available&&y.shift?.end_next_day)return{available:true,shift:y.shift};return{available:false,shift:x?.shift||null};}
async function getContext(env){const[profile,skills,experience,education,certifications,achievements,workshops,services,availability]=await Promise.all([env.DB.prepare("SELECT * FROM profile WHERE id=1").first(),env.DB.prepare("SELECT name,category FROM skills ORDER BY sort_order").all(),env.DB.prepare("SELECT meta,title,summary,note FROM experience ORDER BY sort_order").all(),env.DB.prepare("SELECT meta,title,summary FROM education ORDER BY sort_order").all(),env.DB.prepare("SELECT title,summary FROM certifications ORDER BY sort_order").all(),env.DB.prepare("SELECT meta,title,summary FROM achievements ORDER BY sort_order").all(),env.DB.prepare("SELECT title,role,organizer,date,description FROM workshops ORDER BY sort_order").all(),env.DB.prepare("SELECT name,description FROM services ORDER BY sort_order").all(),getAvailabilityStatus(env)]);const db=(services.results||[]).map(s=>`${s.name}${s.description?`: ${s.description}`:""}`);const serviceList=[...new Set([...SERVICES,...db])];return{profile,availability,services:serviceList,text:`Naveen: ${profile?.full_name||"Naveen Shankar D"}\nTitle: ${profile?.title||"Network Engineer"}\nLocation: ${profile?.location||""}\nBio: ${profile?.bio||""}\nEmail: ${profile?.email||""}\n\nServices:\n${serviceList.map(s=>`- ${s}`).join("\n")}\n\nSkills: ${(skills.results||[]).map(s=>s.name).join(", ")}\nExperience:\n${(experience.results||[]).map(e=>`- ${e.title}: ${e.summary||""}`).join("\n")}\nEducation:\n${(education.results||[]).map(e=>`- ${e.title}: ${e.summary||""}`).join("\n")}\nCertifications:\n${(certifications.results||[]).map(c=>`- ${c.title}: ${c.summary||""}`).join("\n")}\nAchievements:\n${(achievements.results||[]).map(a=>`- ${a.title}: ${a.summary||""}`).join("\n")}\nWorkshops / lectures:\n${(workshops.results||[]).map(w=>`- ${w.title} (${w.date||""}): ${w.description||""}`).join("\n")}\nLive availability: ${availability.available?`Naveen is available now on ${availability.shift?.label||"his shift"}.`:"Naveen is offline/unavailable right now based on his rotational schedule."}`};}
function bookingIntent(m){return/\b(book|booking|schedule|appointment|reserve|hire|consultation|session|lecture|workshop|guest appearance|training)\b/i.test(m);}
function priceIntent(m){return/\b(price|pricing|cost|fee|fees|rate|rates|how much|charge|charges)\b/i.test(m);}
function safetyReply(m){return EXPLICIT_RE.test(m)?"I'm keeping Sana's corner respectful. 😊💛 I can't help with sexual, nude, or explicit content, but I'm very happy to chat, help with Naveen's work, or help with something useful instead.":null;}
function timeReply(m,local,india,country){if(!/\b(what time|current time|time is it|time now|local time)\b/i.test(m))return null;return country!=="IN"?`It's ${local.text} for you right now, and it's ${india.text} in India. 🇮🇳⏰`:`It's ${local.text} for you right now. ⏰`;}

async function extractBooking(env,message,timezone){if(!env.AI)return null;const r=await env.AI.run("@cf/meta/llama-4-scout-17b-16e-instruct",{messages:[{role:"system",content:`Extract only values explicitly present in the latest user message. Return ONLY JSON: {"wants_booking":false,"service":null,"name":null,"email":null,"phone":null,"booking_type":null,"hours":null,"topic":null,"participants":null,"preferred_date":null,"preferred_time":null,"price_requested":false,"details":null}. Do not invent. booking_type is online or offline when stated. hours and participants are numbers when stated. timezone=${JSON.stringify(timezone)}. Services=${SERVICES.join(", ")}.`},{role:"user",content:message}]});try{return JSON.parse(cleanAiText(r).replace(/^```json\s*|\s*```$/g,""));}catch{return null;}}
async function getDraft(env,session){return env.DB.prepare("SELECT * FROM sana_booking_drafts WHERE session_id=? ORDER BY id DESC LIMIT 1").bind(session).first();}
async function saveDraft(env,session,d){const ts=now();const old=await getDraft(env,session);const vals=[d.service,d.name,d.email,d.phone,d.booking_type,d.hours,d.topic,d.participants,d.preferred_date,d.preferred_time,d.timezone,d.details_json,d.price_requested?1:0,ts];if(old){await env.DB.prepare("UPDATE sana_booking_drafts SET service=?,name=?,email=?,phone=?,booking_type=?,hours=?,topic=?,participants=?,preferred_date=?,preferred_time=?,timezone=?,details_json=?,price_requested=?,updated_at=? WHERE id=?").bind(...vals,old.id).run();}else{await env.DB.prepare("INSERT INTO sana_booking_drafts(session_id,service,name,email,phone,booking_type,hours,topic,participants,preferred_date,preferred_time,timezone,details_json,price_requested,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(session,...vals.slice(0,13),vals[13],ts).run();}}
function missing(d){return["service","name","email","phone","booking_type","hours","topic","participants","preferred_date","preferred_time"].filter(k=>d[k]===null||d[k]===undefined||d[k]==="");}
function label(k){return{service:"the service you'd like",name:"your name",email:"your email",phone:"your phone number",booking_type:"whether you want it online or offline",hours:"how many hours you need",topic:"the topic",participants:"the number of participants",preferred_date:"your preferred date",preferred_time:"your preferred time"}[k]||k;}
async function slotAvailable(env,date,time,hours){const start=timeToMinutes(time);const duration=Math.max(.5,Number(hours)||1);if(start===null||!date)return true;const{results}=await env.DB.prepare("SELECT preferred_time,hours,status FROM sana_bookings WHERE preferred_date=? AND status NOT IN ('cancelled','rejected')").bind(date).all();const end=start+duration*60;return!(results||[]).some(b=>{const s=timeToMinutes(b.preferred_time);const e=s===null?s:s+Math.max(.5,Number(b.hours)||1)*60;return s!==null&&start<e&&s<end;});}
function trackingCode(){return`NS-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;}
async function sendVerification(env,email,code,draft){if(!env.RESEND_API_KEY)return false;const from=env.SANA_FROM_EMAIL||"onboarding@resend.dev";const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${env.RESEND_API_KEY}`},body:JSON.stringify({from:`Sana <${from}>`,to:[email],subject:"Verify your Sana booking request",html:`<p>Hi ${draft.name||"there"},</p><p>Your Sana verification code is:</p><h2 style="letter-spacing:4px">${code}</h2><p>It expires in 10 minutes. The booking is created only after verification.</p><p>${draft.service||""} · ${draft.preferred_date||""} · ${draft.preferred_time||""}</p>`})});return r.ok;}
async function finalizeDraft(env,draft){if(!(await slotAvailable(env,draft.preferred_date,draft.preferred_time,draft.hours)))return{conflict:true};const code=trackingCode(),ts=now();await env.DB.prepare(`INSERT INTO sana_bookings(session_id,service,name,email,phone,preferred_date,preferred_time,timezone,details_json,status,created_at,updated_at,booking_type,hours,topic,participants,tracking_code,price_requested,email_verified,email_verified_at) VALUES(?,?,?,?,?,?,?,?,?,'new',?,?,?,?,?,?,?,?,1,?)`).bind(draft.session_id,draft.service,draft.name,draft.email,draft.phone,draft.preferred_date,draft.preferred_time,draft.timezone,draft.details_json,ts,ts,draft.booking_type,draft.hours,draft.topic,draft.participants,code,draft.price_requested,ts).run();await env.DB.prepare("DELETE FROM sana_booking_drafts WHERE id=?").bind(draft.id).run();return{tracking_code:code};}

async function handlePublicChat(request,env){if(!env.AI)return json(request,{error:"Sana isn't configured yet"},400);const body=await request.json().catch(()=>({}));const message=typeof body.message==="string"?body.message.trim():"";if(!message||message.length>1000)return json(request,{error:"Please send a message up to 1000 characters."},400);const session=await ensureSession(env,request);const timezone=timezoneFromRequest(request);const local=partsForTimezone(timezone),india=partsForTimezone("Asia/Kolkata");const country=request.headers.get("CF-IPCountry")||"IN";const existing=await env.DB.prepare("SELECT sender,message FROM sana_messages WHERE session_id=? AND conversation_id IS NULL ORDER BY id DESC LIMIT 8").bind(session).all();const history=(existing.results||[]).reverse().map(m=>({role:m.sender==="visitor"?"user":"assistant",content:m.message}));const first=history.length===0;await saveMessage(env,session,null,"visitor",message);
  const safe=safetyReply(message);if(safe){const reply=`${dayGreeting(local.hour)}! ${safe}`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"safety"});}
  const tr=timeReply(message,local,india,country);if(tr){const reply=`${dayGreeting(local.hour)}! ${tr}`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"time",timezone,local_time:local.text});}
  let draft=await getDraft(env,session);const isBooking=!!draft||bookingIntent(message);
  if(isBooking){const extracted=await extractBooking(env,message,timezone).catch(()=>null);const base=draft||{session_id:session,timezone};const merged={session_id:session,service:extracted?.service||base.service||null,name:extracted?.name||base.name||null,email:extracted?.email||base.email||null,phone:extracted?.phone||base.phone||null,booking_type:extracted?.booking_type||base.booking_type||null,hours:extracted?.hours||base.hours||null,topic:extracted?.topic||base.topic||null,participants:extracted?.participants||base.participants||null,preferred_date:extracted?.preferred_date||base.preferred_date||null,preferred_time:extracted?.preferred_time||base.preferred_time||null,timezone:extracted?.timezone||base.timezone||timezone,details_json:extracted?.details||base.details_json||null,price_requested:(extracted?.price_requested||priceIntent(message)||base.price_requested)?1:0};await saveDraft(env,session,merged);draft=await getDraft(env,session);const missingFields=missing(draft);if(missingFields.length){const reply=`${dayGreeting(local.hour)}! ${first?"I'm Sana, Naveen's personal AI assistant. ":""}I've got you 😊 Could you share ${label(missingFields[0])}?`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_collecting",booking_fields:missingFields});}
    if(!(await slotAvailable(env,draft.preferred_date,draft.preferred_time,draft.hours))){const reply=`${dayGreeting(local.hour)}! That slot is already booked, so I don't want to double-book you. 💛 Could you give me another date or time?`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"slot_unavailable"});}
    const code=message.match(/\b(\d{6})\b/)?.[1];if(code&&draft.verification_code_hash&&draft.verification_expires_at>=now()){if((await sha256(code))===draft.verification_code_hash){const final=await finalizeDraft(env,draft);if(final.conflict){const reply=`${dayGreeting(local.hour)}! That slot was just taken. 😅 Let's pick another date or time.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"slot_unavailable"});}const reply=`${dayGreeting(local.hour)}! Perfect — your booking is confirmed. 💛 Your tracking ID is ${final.tracking_code}.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_created",tracking_code:final.tracking_code});}const reply=`${dayGreeting(local.hour)}! That code doesn't look right. Please send the 6-digit code from the email. 😊`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"email_verification_required"});}
    if(/\b(send|resend)\b.*\b(code|verification)\b/i.test(message)||!draft.verification_code_hash||!draft.verification_expires_at||draft.verification_expires_at<now()){const verification=String(Math.floor(100000+Math.random()*900000));const hash=await sha256(verification);const expires=now()+VERIFICATION_TTL_MS;await env.DB.prepare("UPDATE sana_booking_drafts SET verification_code_hash=?,verification_expires_at=?,updated_at=? WHERE id=?").bind(hash,expires,now(),draft.id).run();const sent=await sendVerification(env,draft.email,verification,draft);if(!sent){const reply=`${dayGreeting(local.hour)}! Your details are ready, but email verification isn't configured yet. I haven't created the booking, so nothing fake was added. 💛`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"email_verification_unavailable"});}const reply=`${dayGreeting(local.hour)}! Lovely — I have everything. 💛 I sent a 6-digit verification code to ${draft.email}. Send it here and I'll create your booking and give you a tracking ID.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"email_verification_required"});}
    const reply=`${dayGreeting(local.hour)}! I’m ready for the verification code from your email. 😊`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"email_verification_required"});
  }
  if(priceIntent(message)){const reply=`${dayGreeting(local.hour)}! Pricing depends on the service and details. Once Naveen reviews it, he'll email you with the price. 😊`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"pricing"});}
  const context=await getContext(env);const availability=context.availability.available?"Naveen is currently available.":"Naveen is currently offline/unavailable.";const system=`You are Sana, Naveen's personal AI assistant. Never call yourself a portfolio assistant. Be warm, playful, lovely, diplomatic and natural; never stiff or formal. Visitor timezone=${timezone}; local time=${local.text}; India time=${india.text}. ${country!=="IN"?"Mention India time naturally when useful.":""} ${first?"This is the first reply, so introduce yourself once as Sana, Naveen's personal AI assistant.":"Do not re-introduce yourself unless asked."} Start answers with a short local-time greeting, but never repeat your identity. Never claim to be human. React warmly to affection without sexual escalation. Sexual, nude or explicit requests are refused. For pricing, say Naveen will email after review. For booking, use the booking flow. For live connection, use the live connection controls. ${availability}\nFACTS:\n${context.text}`;const result=await env.AI.run("@cf/meta/llama-4-scout-17b-16e-instruct",{messages:[{role:"system",content:system},...history,{role:"user",content:message}]});let reply=cleanAiText(result);if(!reply)return json(request,{error:"No response generated"},502);if(!/^(hi|good morning|good afternoon|good evening)\b/i.test(reply))reply=`${dayGreeting(local.hour)}! ${reply}`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"chat",timezone,local_time:local.text});}

async function handlePresence(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const ts=now();await env.DB.prepare(`INSERT INTO sana_presence(id,online,last_seen_at,admin_username,updated_at) VALUES(1,1,?,?,?) ON CONFLICT(id) DO UPDATE SET online=1,last_seen_at=excluded.last_seen_at,admin_username=excluded.admin_username,updated_at=excluded.updated_at`).bind(ts,auth.username,ts).run();return json(request,{online:true,last_seen_at:ts});}
async function handleStatus(request,env){const r=await env.DB.prepare("SELECT online,last_seen_at FROM sana_presence WHERE id=1").first();return json(request,{online:!!r&&r.online===1&&now()-r.last_seen_at<ONLINE_WINDOW_MS,last_seen_at:r?.last_seen_at||null,services:SERVICES});}
async function handleConnect(request,env){const session=await ensureSession(env,request);const p=await env.DB.prepare("SELECT online,last_seen_at FROM sana_presence WHERE id=1").first();const online=!!p&&p.online===1&&now()-p.last_seen_at<ONLINE_WINDOW_MS;if(!online)return json(request,{approved:false,offline:true,message:"Naveen is offline. I can pass a message to him for you."});const old=await env.DB.prepare("SELECT id,status,conversation_id,expires_at FROM sana_connect_requests WHERE session_id=? ORDER BY id DESC LIMIT 1").bind(session).first();if(old&&old.status==="approved"&&old.conversation_id)return json(request,{approved:true,conversation_id:old.conversation_id});const ts=now(),expires=ts+CONNECT_WINDOW_MS;const r=await env.DB.prepare("INSERT INTO sana_connect_requests(session_id,status,conversation_id,created_at,expires_at,updated_at) VALUES(?, 'pending', NULL, ?, ?, ?)").bind(session,ts,expires,ts).run();return json(request,{approved:false,request_id:r.meta.last_row_id,expires_at:expires,countdown_seconds:180});}
async function handleConnectStatus(request,env,id){const session=await ensureSession(env,request);const r=await env.DB.prepare("SELECT id,status,conversation_id,expires_at FROM sana_connect_requests WHERE id=? AND session_id=?").bind(id,session).first();if(!r)return json(request,{error:"Connection request not found"},404);if(r.status==="pending"&&r.expires_at<now()){await env.DB.prepare("UPDATE sana_connect_requests SET status='expired',updated_at=? WHERE id=?").bind(now(),id).run();r.status="expired";}return json(request,{approved:r.status==="approved",status:r.status,conversation_id:r.conversation_id,expires_at:r.expires_at,countdown_seconds:Math.max(0,Math.ceil((r.expires_at-now())/1000))});}
async function handlePublicMessages(request,env){const session=await ensureSession(env,request);const id=new URL(request.url).searchParams.get("conversation_id");if(!id)return json(request,{messages:[]});const{results}=await env.DB.prepare("SELECT id,sender,message,created_at FROM sana_messages WHERE conversation_id=? AND session_id=? ORDER BY id ASC LIMIT 200").bind(id,session).all();return json(request,{messages:results||[]});}
async function handlePublicMessage(request,env){const session=await ensureSession(env,request);const b=await request.json().catch(()=>({}));const id=typeof b.conversation_id==="string"?b.conversation_id:"";const message=typeof b.message==="string"?b.message.trim():"";if(!id||!message||message.length>1000)return json(request,{error:"Invalid message"},400);const access=await env.DB.prepare("SELECT id FROM sana_connect_requests WHERE conversation_id=? AND session_id=? AND status='approved' LIMIT 1").bind(id,session).first();if(!access)return json(request,{error:"Live chat is not connected"},403);if(EXPLICIT_RE.test(message))return json(request,{success:true,blocked:true});await saveMessage(env,session,id,"visitor",message);return json(request,{success:true});}
async function handleOfflineMessage(request,env){const session=await ensureSession(env,request);const b=await request.json().catch(()=>({}));const message=typeof b.message==="string"?b.message.trim():"";if(!message||message.length>2000)return json(request,{error:"Message is required"},400);await saveMessage(env,session,null,"visitor",message);return json(request,{success:true});}
async function handleAdminRequests(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const{results}=await env.DB.prepare(`SELECT r.*,s.timezone,s.country FROM sana_connect_requests r LEFT JOIN sana_sessions s ON s.id=r.session_id WHERE r.status IN ('pending','approved') ORDER BY r.id DESC LIMIT 50`).all();return json(request,{requests:results||[]});}
async function handleApprove(request,env,id,approve){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const row=await env.DB.prepare("SELECT * FROM sana_connect_requests WHERE id=?").bind(id).first();if(!row)return json(request,{error:"Request not found"},404);if(!approve){await env.DB.prepare("UPDATE sana_connect_requests SET status='rejected',updated_at=? WHERE id=?").bind(now(),id).run();return json(request,{success:true,status:"rejected"});}const conversationId=`sana-${id}-${crypto.randomUUID()}`;await env.DB.prepare("UPDATE sana_connect_requests SET status='approved',conversation_id=?,updated_at=? WHERE id=?").bind(conversationId,now(),id).run();await saveMessage(env,row.session_id,conversationId,"sana","Hi! Naveen is connected now. You can chat with him here. 👋");return json(request,{success:true,status:"approved",conversation_id:conversationId});}
async function handleAdminMessages(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const id=new URL(request.url).searchParams.get("conversation_id");if(!id)return json(request,{messages:[]});const{results}=await env.DB.prepare("SELECT id,sender,message,created_at FROM sana_messages WHERE conversation_id=? ORDER BY id ASC LIMIT 200").bind(id).all();return json(request,{messages:results||[]});}
async function handleAdminSendMessage(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const b=await request.json().catch(()=>({}));const id=typeof b.conversation_id==="string"?b.conversation_id:"";const message=typeof b.message==="string"?b.message.trim():"";if(!id||!message||message.length>2000)return json(request,{error:"Invalid message"},400);const row=await env.DB.prepare("SELECT id FROM sana_connect_requests WHERE conversation_id=? AND status='approved' LIMIT 1").bind(id).first();if(!row)return json(request,{error:"Conversation not active"},404);const s=await env.DB.prepare("SELECT session_id FROM sana_connect_requests WHERE id=?").bind(row.id).first();await saveMessage(env,s.session_id,id,"naveen",message);return json(request,{success:true});}
async function handleBookings(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const{results}=await env.DB.prepare("SELECT * FROM sana_bookings ORDER BY id DESC LIMIT 100").all();return json(request,{bookings:results||[]});}
async function handleBookingUpdate(request,env,id){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const b=await request.json().catch(()=>({}));const allowed=["new","reviewing","confirmed","completed","cancelled","rejected","price_requested"];const status=allowed.includes(b.status)?b.status:null;const price=b.price_amount===null||b.price_amount===""?null:Number(b.price_amount);const note=typeof b.admin_note==="string"?b.admin_note.slice(0,2000):null;const row=await env.DB.prepare("SELECT * FROM sana_bookings WHERE id=?").bind(id).first();if(!row)return json(request,{error:"Booking not found"},404);await env.DB.prepare("UPDATE sana_bookings SET status=COALESCE(?,status),price_amount=?,price_currency=?,admin_note=COALESCE(?,admin_note),updated_at=? WHERE id=?").bind(status,Number.isFinite(price)?price:null,typeof b.price_currency==="string"?b.price_currency.slice(0,8):(row.price_currency||"INR"),note,now(),id).run();return json(request,{success:true});}

export default{async fetch(request,env,ctx){if(request.method==="OPTIONS")return new Response(null,{headers:corsHeaders(request)});const path=new URL(request.url).pathname;try{if(path==="/public/chat"&&request.method==="POST")return handlePublicChat(request,env);if(path==="/public/sana/status"&&request.method==="GET")return handleStatus(request,env);if(path==="/public/sana/connect"&&request.method==="POST")return handleConnect(request,env);if(path.startsWith("/public/sana/connect/")&&request.method==="GET")return handleConnectStatus(request,env,parseInt(path.split("/").pop(),10));if(path==="/public/sana/messages"&&request.method==="GET")return handlePublicMessages(request,env);if(path==="/public/sana/message"&&request.method==="POST")return handlePublicMessage(request,env);if(path==="/public/sana/offline-message"&&request.method==="POST")return handleOfflineMessage(request,env);if(path==="/admin/sana/heartbeat"&&request.method==="POST")return handlePresence(request,env);if(path==="/admin/sana/requests"&&request.method==="GET")return handleAdminRequests(request,env);if(/^\/admin\/sana\/requests\/\d+\/(approve|reject)$/.test(path)&&request.method==="POST")return handleApprove(request,env,parseInt(path.split("/")[4],10),path.endsWith("/approve"));if(path==="/admin/sana/messages"&&request.method==="GET")return handleAdminMessages(request,env);if(path==="/admin/sana/message"&&request.method==="POST")return handleAdminSendMessage(request,env);if(path==="/admin/sana/bookings"&&request.method==="GET")return handleBookings(request,env);if(/^\/admin\/sana\/bookings\/\d+$/.test(path)&&request.method==="PUT")return handleBookingUpdate(request,env,parseInt(path.split("/").pop(),10));return existingWorker.fetch(request,env,ctx);}catch(error){return json(request,{error:"Sana request failed",detail:String(error)},500);}}};