import existingWorker from "./index.js";
import { verifySessionToken } from "./auth.js";

const SERVICES = ["Networking","Live session","Lectures","Guest appearance","Web development","Self-development coaching","Career path guidance","Resume / CV review","Interview preparation","Network troubleshooting consultation","Technical mentoring","Workshop / training"];
const ONLINE_WINDOW_MS = 45 * 1000;
const CONNECT_WINDOW_MS = 3 * 60 * 1000;

function corsHeaders(request) { const origin=request.headers.get("Origin"); const allowed=["https://naveenshankar.in","https://www.naveenshankar.in","https://admin.naveenshankar.in"]; return {"Access-Control-Allow-Origin":allowed.includes(origin)?origin:allowed[0],"Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Sana-Session,X-Sana-Timezone","Access-Control-Allow-Credentials":"true",Vary:"Origin"}; }
function json(request,data,status=200,extraHeaders={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...corsHeaders(request),...extraHeaders}});}
function now(){return Date.now();}
function timezoneFromRequest(request){return request.headers.get("X-Sana-Timezone")||"Asia/Kolkata";}
function partsForTimezone(timeZone,date=new Date()){try{const text=new Intl.DateTimeFormat("en-US",{timeZone,weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).format(date);const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone,hour:"numeric",hour12:false}).format(date));return{text,hour,valid:true};}catch{const fallback=partsForTimezone("Asia/Kolkata",date);return{...fallback,valid:false};}}
function dayGreeting(hour){if(hour>=5&&hour<12)return"Good morning";if(hour>=12&&hour<17)return"Good afternoon";if(hour>=17&&hour<21)return"Good evening";return"Hi";}
function getSessionId(request){const supplied=request.headers.get("X-Sana-Session");if(supplied&&/^[a-zA-Z0-9_-]{12,100}$/.test(supplied))return supplied;const ip=request.headers.get("CF-Connecting-IP")||"unknown";const ua=request.headers.get("User-Agent")||"unknown";return`${ip}:${ua}`;}
async function sha256(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function sessionId(request){const supplied=request.headers.get("X-Sana-Session");if(supplied&&/^[a-zA-Z0-9_-]{12,100}$/.test(supplied))return supplied;return(await sha256(getSessionId(request))).slice(0,40);}
async function ensureSession(env,request){const id=await sessionId(request),timezone=timezoneFromRequest(request),country=request.headers.get("CF-IPCountry")||"";await env.DB.prepare(`INSERT INTO sana_sessions (id,timezone,country,created_at,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET timezone=excluded.timezone,country=excluded.country,updated_at=excluded.updated_at`).bind(id,timezone,country,now(),now()).run();return id;}
function cleanAiText(result){return(result?.response||result?.output_text||(Array.isArray(result?.output)&&result.output.find(o=>o.content)?.content?.[0]?.text)||"").trim();}
async function getSanaContext(env){const[profile,skills,experience,education,certifications,achievements,workshops,services,availability]=await Promise.all([env.DB.prepare("SELECT * FROM profile WHERE id=1").first(),env.DB.prepare("SELECT name,category FROM skills ORDER BY sort_order ASC").all(),env.DB.prepare("SELECT meta,title,summary,note FROM experience ORDER BY sort_order ASC").all(),env.DB.prepare("SELECT meta,title,summary FROM education ORDER BY sort_order ASC").all(),env.DB.prepare("SELECT title,summary FROM certifications ORDER BY sort_order ASC").all(),env.DB.prepare("SELECT meta,title,summary FROM achievements ORDER BY sort_order ASC").all(),env.DB.prepare("SELECT title,role,organizer,date,description FROM workshops ORDER BY sort_order ASC").all(),env.DB.prepare("SELECT name,description FROM services ORDER BY sort_order ASC").all(),getAvailabilityStatus(env)]);const dbServices=(services.results||[]).map(s=>`${s.name}${s.description?`: ${s.description}`:""}`),serviceList=[...new Set([...SERVICES,...dbServices])];return{profile,availability,services:serviceList,text:`Naveen: ${profile?.full_name||"Naveen Shankar D"}\nTitle: ${profile?.title||"Network Engineer"}\nLocation: ${profile?.location||""}\nBio: ${profile?.bio||""}\nEmail: ${profile?.email||""}\n\nServices offered:\n${serviceList.map(s=>`- ${s}`).join("\n")}\n\nSkills: ${(skills.results||[]).map(s=>s.name).join(", ")}\n\nExperience:\n${(experience.results||[]).map(e=>`- ${e.title} (${e.meta||""}): ${e.summary||""}${e.note?` ${e.note}`:""}`).join("\n")}\n\nEducation:\n${(education.results||[]).map(e=>`- ${e.title} (${e.meta||""}): ${e.summary||""}`).join("\n")}\n\nCertifications:\n${(certifications.results||[]).map(c=>`- ${c.title}: ${c.summary||""}`).join("\n")}\n\nAchievements:\n${(achievements.results||[]).map(a=>`- ${a.title} (${a.meta||""}): ${a.summary||""}`).join("\n")}\n\nWorkshops / lectures:\n${(workshops.results||[]).map(w=>`- ${w.title} (${w.role||""}, ${w.organizer||""}, ${w.date||""}): ${w.description||""}`).join("\n")}\n\nLive availability:\n${availability.available&&availability.shift?`Naveen is available now on ${availability.shift.label}, ${availability.shift.start_time}-${availability.shift.end_time}${availability.shift.end_next_day?" next day":""} IST.`:"Naveen is offline/unavailable right now based on his rotational schedule."}`.trim()};}
async function getAvailabilityStatus(env){const{dateStr:today,minutesOfDay}=getISTParts(),yesterday=new Date(Date.now()-86400000),{dateStr:yesterdayStr}=getISTParts(yesterday);const[todayEntry,yesterdayEntry,shiftTypesRes]=await Promise.all([env.DB.prepare("SELECT shift_type FROM availability WHERE date=?").bind(today).first(),env.DB.prepare("SELECT shift_type FROM availability WHERE date=?").bind(yesterdayStr).first(),env.DB.prepare("SELECT * FROM shift_types").all()]);const shiftMap={};(shiftTypesRes.results||[]).forEach(s=>shiftMap[s.code]=s);const evaluate=entry=>{if(!entry)return null;const shift=shiftMap[entry.shift_type];if(!shift||shift.is_off)return{available:false,shift};const start=timeToMinutes(shift.start_time),end=timeToMinutes(shift.end_time),within=shift.end_next_day?minutesOfDay>=start||minutesOfDay<end:minutesOfDay>=start&&minutesOfDay<end;return{available:within,shift};};const tr=evaluate(todayEntry),yr=evaluate(yesterdayEntry);if(tr?.available)return{available:true,shift:tr.shift};if(yr?.available&&yr.shift?.end_next_day)return{available:true,shift:yr.shift};return{available:false,shift:tr?.shift||null};}
function getISTParts(date=new Date()){const text=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(date),get=t=>text.find(p=>p.type===t)?.value;return{dateStr:`${get("year")}-${get("month")}-${get("day")}`,minutesOfDay:Number(get("hour"))*60+Number(get("minute"))};}
function timeToMinutes(hhmm){if(!hhmm)return null;const[h,m]=hhmm.split(":").map(Number);return h*60+m;}
async function adminAuth(request,env){const auth=request.headers.get("Authorization")||"",token=auth.startsWith("Bearer ")?auth.slice(7):null;return token?verifySessionToken(env.SESSION_SECRET,token):null;}
async function saveMessage(env,session,conversationId,sender,message){await env.DB.prepare("INSERT INTO sana_messages (session_id,conversation_id,sender,message,created_at) VALUES (?,?,?,?,?)").bind(session,conversationId||null,sender,message,now()).run();}
function normalizeType(v){v=String(v||"").trim().toLowerCase();return v==="online"||v==="offline"?v:null;}
function normalizeParticipants(v){const n=Number(v);return Number.isInteger(n)&&n>0&&n<=1000?n:null;}
function normalizeHours(v){const n=Number(v);return Number.isFinite(n)&&n>0&&n<=24?n:null;}
function parseRequestedStart(date,time){const m=String(time||"").match(/(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(!m||!date)return null;let h=Number(m[1]),min=Number(m[2]||0),ap=(m[3]||"").toLowerCase();if(ap==="pm"&&h<12)h+=12;if(ap==="am"&&h===12)h=0;if(h>23||min>59)return null;const iso=String(date).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!iso)return null;const d=new Date(Date.UTC(Number(iso[1]),Number(iso[2])-1,Number(iso[3]),h,min));return Number.isNaN(d.getTime())?null:d.getTime();}
function overlap(aStart,aHours,bStart,bHours){const a=Number(aStart),b=Number(bStart),ah=Number(aHours||1)*3600000,bh=Number(bHours||1)*3600000;return a<b+bh&&b<a+ah;}
async function extractBooking(env,message,timezone){if(!env.AI)return null;const result=await env.AI.run("@cf/meta/llama-4-scout-17b-16e-instruct",{messages:[{role:"system",content:`Extract booking information. Return ONLY valid JSON with keys: wants_booking,service,name,email,phone,booking_type,hours,topic,participants,preferred_date,preferred_time,timezone,details. Do not invent. booking_type must be online or offline when explicitly provided. hours and participants must be numbers when explicitly provided. timezone defaults to ${JSON.stringify(timezone)}. Known services: ${SERVICES.join(", ")}.`},{role:"user",content:message}]});const text=cleanAiText(result).replace(/^```json\s*|\s*```$/g,"");try{const data=JSON.parse(text);return data.wants_booking?data:null;}catch{return null;}}
async function createOrUpdateDraft(env,session,data,timezone){const previous=await env.DB.prepare("SELECT * FROM sana_bookings WHERE session_id=? AND status='draft' ORDER BY id DESC LIMIT 1").bind(session).first(),merged={service:data.service||previous?.service||null,name:data.name||previous?.name||null,email:data.email||previous?.email||null,phone:data.phone||previous?.phone||null,booking_type:normalizeType(data.booking_type||previous?.booking_type),hours:normalizeHours(data.hours||previous?.hours),topic:data.topic||previous?.topic||null,participants:normalizeParticipants(data.participants||previous?.participants),preferred_date:data.preferred_date||previous?.preferred_date||null,preferred_time:data.preferred_time||previous?.preferred_time||null,timezone:data.timezone||previous?.timezone||timezone,details:data.details||previous?.details_json||null},ts=now();if(previous){await env.DB.prepare("UPDATE sana_bookings SET service=?,name=?,email=?,phone=?,booking_type=?,hours=?,topic=?,participants=?,preferred_date=?,preferred_time=?,timezone=?,details_json=?,updated_at=? WHERE id=?").bind(merged.service,merged.name,merged.email,merged.phone,merged.booking_type,merged.hours,merged.topic,merged.participants,merged.preferred_date,merged.preferred_time,merged.timezone,merged.details,ts,previous.id).run();return{...merged,id:previous.id};}const r=await env.DB.prepare("INSERT INTO sana_bookings (session_id,service,name,email,phone,booking_type,hours,topic,participants,preferred_date,preferred_time,timezone,details_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?)").bind(session,merged.service,merged.name,merged.email,merged.phone,merged.booking_type,merged.hours,merged.topic,merged.participants,merged.preferred_date,merged.preferred_time,merged.timezone,merged.details,ts,ts).run();return{...merged,id:r.meta.last_row_id};}
async function slotConflict(env,booking){const start=parseRequestedStart(booking.preferred_date,booking.preferred_time);if(!start)return false;const rows=await env.DB.prepare("SELECT id,preferred_date,preferred_time,hours,status FROM sana_bookings WHERE id!=? AND status IN ('new','confirmed','pending') AND preferred_date=? AND booking_type=?").bind(booking.id,booking.preferred_date,booking.booking_type).all();return(rows.results||[]).some(r=>{const other=parseRequestedStart(r.preferred_date,r.preferred_time);return other&&overlap(start,booking.hours||1,other,r.hours||1);});}
function missingFields(b){return["service","name","email","phone","booking_type","hours","topic","participants","preferred_date","preferred_time"].filter(k=>b[k]===null||b[k]===undefined||b[k]==="");}
const labels={service:"the service you'd like",name:"your name",email:"your email",phone:"your phone number",booking_type:"whether you'd like it online or offline",hours:"how many hours you need",topic:"the topic",participants:"the number of participants",preferred_date:"your preferred date",preferred_time:"your preferred time"};

async function handlePublicChat(request,env){if(!env.AI)return json(request,{error:"Sana isn't configured yet"},400);const body=await request.json().catch(()=>({})),message=typeof body.message==="string"?body.message.trim():"";if(!message||message.length>1000)return json(request,{error:"Please send a message up to 1000 characters."},400);const session=await ensureSession(env,request),timezone=timezoneFromRequest(request),local=partsForTimezone(timezone),india=partsForTimezone("Asia/Kolkata"),country=request.headers.get("CF-IPCountry")||"IN",context=await getSanaContext(env),existing=await env.DB.prepare("SELECT sender,message FROM sana_messages WHERE session_id=? AND conversation_id IS NULL ORDER BY id DESC LIMIT 10").bind(session).all(),history=(existing.results||[]).reverse().map(m=>({role:m.sender==="visitor"?"user":"assistant",content:m.message}));await saveMessage(env,session,null,"visitor",message);const lower=message.toLowerCase();
const sexual=/\b(sex|sexual|nude|nudes|nudity|porn|pornography|xxx|erotic|horny|blowjob|handjob|masturbat|fuck|dick|pussy|boobs|breasts|anal|onlyfans)\b/i.test(message);if(sexual){const reply=`${dayGreeting(local.hour)}! 😊 I'm happy to chat with you, but I keep things respectful and I can't help with sexual or nude content. We can talk about Naveen, his work, services, learning, careers, or something fun instead. 💙`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"blocked_content"});}
const booking=await extractBooking(env,message,timezone).catch(()=>null);if(booking){const draft=await createOrUpdateDraft(env,session,booking,timezone),missing=missingFields(draft);if(missing.length){const indiaNote=country!=="IN"?` It's ${dayGreeting(india.hour).toLowerCase()} in India right now.`:"",reply=`${dayGreeting(local.hour)}! 😊 I'm Sana, Naveen's personal AI assistant.${indiaNote} I can arrange that for you. Could you share ${labels[missing[0]]}?`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_collecting",booking_fields:missing,booking_id:draft.id});}if(await slotConflict(env,draft)){const reply=`${dayGreeting(local.hour)}! 😊 That slot is already requested for another ${draft.booking_type} booking. Please give me another date or time and I'll check it for you.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_slot_conflict",booking_id:draft.id});}const ts=now();await env.DB.prepare("UPDATE sana_bookings SET status='new',updated_at=? WHERE id=?").bind(ts,draft.id).run();const reply=`${dayGreeting(local.hour)}! 😊 Perfect — I've recorded your ${draft.service} request for ${draft.preferred_date} at ${draft.preferred_time} (${draft.timezone}), ${draft.booking_type}, ${draft.hours} hour(s), ${draft.participants} participant(s). Your request ID is NS-${draft.id}. Naveen will review the request and email you about confirmation and pricing.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_created",booking_id:draft.id,tracking_id:`NS-${draft.id}`});}
const live=/\b(live|talk|connect|speak|call|chat with naveen|talk to naveen|connect me)\b/i.test(message);if(live){const presence=await env.DB.prepare("SELECT * FROM sana_presence WHERE id=1").first(),online=!!presence&&Number(presence.online)===1&&now()-Number(presence.last_seen_at||0)<=ONLINE_WINDOW_MS;if(!online){const reply=`${dayGreeting(local.hour)}! 😊 Naveen is offline right now. I can leave him a message for you, or you can come back when he's online.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"naveen_offline"});}const expires=now()+CONNECT_WINDOW_MS,conversationId=crypto.randomUUID();await env.DB.prepare("INSERT INTO sana_connect_requests (session_id,status,conversation_id,created_at,expires_at,updated_at) VALUES (?,'pending',?,?,?,?,?)".replace("VALUES (?,'pending',?,?,?,?,?)","VALUES (?, 'pending', ?, ?, ?, ?)")).bind(session,conversationId,now(),expires,now()).run();const reply=`${dayGreeting(local.hour)}! 😊 Naveen is online. I've sent him a connection request. I'll keep this connection open for about 3 minutes while he responds.`;await saveMessage(env,session,conversationId,"sana",reply);return json(request,{reply,action:"connect_requested",conversation_id:conversationId,expires_at:expires});}
const price=/\b(price|pricing|cost|fee|fees|how much|charge|charges)\b/i.test(message),greeting=dayGreeting(local.hour),indiaNote=country!=="IN"?` It's ${dayGreeting(india.hour).toLowerCase()} in India right now.`:"",system=`You are Sana, Naveen Shankar D's personal AI assistant. You are NOT a portfolio assistant and never call yourself a portfolio assistant. Introduce yourself naturally only when needed; do not repeat your name or identity in every response. Be warm, playful, loving, friendly, diplomatic and human-like, but never pretend to be human. You can react warmly to compliments or affection without claiming a human relationship. Never engage in sexual, nude, erotic or explicit content; politely redirect. Answer simple questions such as time/date using the visitor timezone supplied below. If the visitor is outside India, you may naturally mention the current India time once when relevant. Naveen's services include networking, live sessions, lectures, guest appearances, web development, self-development coaching, career path guidance, resume/CV review, interview preparation, technical mentoring, network troubleshooting and workshops/training. If asked for price, say Naveen will review the request and email the visitor; do not invent a price. If asked to book, use the booking flow rather than claiming a booking is confirmed. If asked to connect with Naveen, use the live connection flow rather than pretending he is available. Keep replies friendly and concise, normally 1-4 short sentences. ${indiaNote}\n\n${context.text}`;try{const result=await env.AI.run("@cf/meta/llama-4-scout-17b-16e-instruct",{messages:[{role:"system",content:system},...history,{role:"user",content:message}]});const reply=cleanAiText(result);if(!reply)return json(request,{error:"No response generated"},502);await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:price?"price_info":"chat",local_time:local.text,india_time:india.text,timezone,country});}catch(e){return json(request,{error:"Chat request failed",detail:String(e)},500);}}

async function handlePresence(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);const body=await request.json().catch(()=>({})),online=!!body.online,username=auth.username||auth.email||"admin";await env.DB.prepare("INSERT INTO sana_presence (id,online,last_seen_at,admin_username,updated_at) VALUES (1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET online=excluded.online,last_seen_at=excluded.last_seen_at,admin_username=excluded.admin_username,updated_at=excluded.updated_at").bind(online?1:0,now(),username,now()).run();return json(request,{online,last_seen_at:now()});}
async function handleConnectRequests(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);if(request.method==="GET"){const rows=await env.DB.prepare("SELECT * FROM sana_connect_requests WHERE status='pending' ORDER BY created_at DESC LIMIT 50").all();return json(request,{requests:rows.results||[]});}const body=await request.json().catch(()=>({})),id=Number(body.id),status=["accepted","declined","expired"].includes(body.status)?body.status:null;if(!id||!status)return json(request,{error:"id and valid status required"},400);await env.DB.prepare("UPDATE sana_connect_requests SET status=?,updated_at=? WHERE id=?").bind(status,now(),id).run();return json(request,{ok:true});}
async function handleBookingAdmin(request,env){const auth=await adminAuth(request,env);if(!auth)return json(request,{error:"Unauthorized"},401);if(request.method==="GET"){const rows=await env.DB.prepare("SELECT * FROM sana_bookings ORDER BY created_at DESC LIMIT 100").all();return json(request,{bookings:rows.results||[]});}const body=await request.json().catch(()=>({})),id=Number(body.id);if(!id)return json(request,{error:"id required"},400);const fields=[],values=[],statuses=["draft","new","pending","confirmed","declined","completed","cancelled"];if(body.status&&statuses.includes(body.status)){fields.push("status=?");values.push(body.status);}if(Object.prototype.hasOwnProperty.call(body,"price")){fields.push("price=?");values.push(body.price===null||body.price===""?null:Number(body.price));}if(!fields.length)return json(request,{error:"No valid fields"},400);values.push(now(),id);await env.DB.prepare(`UPDATE sana_bookings SET ${fields.join(",")},updated_at=? WHERE id=?`).bind(...values).run();return json(request,{ok:true});}

export default{async fetch(request,env,ctx){if(request.method==="OPTIONS")return existingWorker.fetch(request,env,ctx);const path=new URL(request.url).pathname;if(path==="/public/chat"&&request.method==="POST")return handlePublicChat(request,env);if(path==="/admin/sana/presence"&&request.method==="POST")return handlePresence(request,env);if(path==="/admin/sana/requests"&&(request.method==="GET"||request.method==="POST"))return handleConnectRequests(request,env);if(path==="/admin/sana/bookings"&&(request.method==="GET"||request.method==="POST"))return handleBookingAdmin(request,env);return existingWorker.fetch(request,env,ctx);}};
