import existingWorker from "./index.js";
import { verifySessionToken } from "./auth.js";

const SERVICES=["Networking","Live session","Lectures","Guest appearance","Web development","Self-development coaching","Career path guidance","Resume / CV review","Interview preparation","Network troubleshooting consultation","Technical mentoring","Workshop / training"];
const ONLINE_WINDOW_MS=45*1000, CONNECT_WINDOW_MS=3*60*1000;
const allowedOrigins=["https://naveenshankar.in","https://www.naveenshankar.in","https://admin.naveenshankar.in"];
function corsHeaders(request){const origin=request.headers.get("Origin");return{"Access-Control-Allow-Origin":allowedOrigins.includes(origin)?origin:allowedOrigins[0],"Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Sana-Session,X-Sana-Timezone","Access-Control-Allow-Credentials":"true",Vary:"Origin"};}
function json(request,data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...corsHeaders(request)}});}
const now=()=>Date.now();
function timezoneFromRequest(r){return r.headers.get("X-Sana-Timezone")||"Asia/Kolkata";}
function partsForTimezone(tz,date=new Date()){try{return{text:new Intl.DateTimeFormat("en-US",{timeZone:tz,weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).format(date),hour:Number(new Intl.DateTimeFormat("en-US",{timeZone:tz,hour:"numeric",hour12:false}).format(date)),valid:true};}catch{const f=partsForTimezone("Asia/Kolkata",date);return{...f,valid:false};}}
function dayGreeting(h){if(h>=5&&h<12)return"Good morning";if(h>=12&&h<17)return"Good afternoon";if(h>=17&&h<21)return"Good evening";return"Hi";}
async function sha256(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function sessionId(r){const s=r.headers.get("X-Sana-Session");if(s&&/^[a-zA-Z0-9_-]{12,100}$/.test(s))return s;return(await sha256(`${r.headers.get("CF-Connecting-IP")||"unknown"}:${r.headers.get("User-Agent")||"unknown"}`)).slice(0,40);}
async function ensureSession(env,r){const id=await sessionId(r),tz=timezoneFromRequest(r),country=r.headers.get("CF-IPCountry")||"";await env.DB.prepare(`INSERT INTO sana_sessions(id,timezone,country,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET timezone=excluded.timezone,country=excluded.country,updated_at=excluded.updated_at`).bind(id,tz,country,now(),now()).run();return id;}
function aiText(x){return(x?.response||x?.output_text||(Array.isArray(x?.output)&&x.output.find(o=>o.content)?.content?.[0]?.text)||"").trim();}
async function getAvailabilityStatus(env){const{dateStr:today,minutesOfDay}=getISTParts(),y=new Date(Date.now()-86400000),{dateStr:yesterdayStr}=getISTParts(y);const[a,b,s]=await Promise.all([env.DB.prepare("SELECT shift_type FROM availability WHERE date=?").bind(today).first(),env.DB.prepare("SELECT shift_type FROM availability WHERE date=?").bind(yesterdayStr).first(),env.DB.prepare("SELECT * FROM shift_types").all()]);const map={};(s.results||[]).forEach(x=>map[x.code]=x);const ev=e=>{if(!e)return null;const sh=map[e.shift_type];if(!sh||sh.is_off)return{available:false,shift:sh};const st=timeToMinutes(sh.start_time),en=timeToMinutes(sh.end_time),ok=sh.end_next_day?minutesOfDay>=st||minutesOfDay<en:minutesOfDay>=st&&minutesOfDay<en;return{available:ok,shift:sh};};const ar=ev(a),br=ev(b);if(ar?.available)return{available:true,shift:ar.shift};if(br?.available&&br.shift?.end_next_day)return{available:true,shift:br.shift};return{available:false,shift:ar?.shift||null};}
function getISTParts(date=new Date()){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(date),g=t=>p.find(x=>x.type===t)?.value;return{dateStr:`${g("year")}-${g("month")}-${g("day")}`,minutesOfDay:Number(g("hour"))*60+Number(g("minute"))};}
function timeToMinutes(v){if(!v)return null;const[h,m]=v.split(":").map(Number);return h*60+m;}
async function saveMessage(env,s,c,sender,msg){await env.DB.prepare("INSERT INTO sana_messages(session_id,conversation_id,sender,message,created_at) VALUES(?,?,?,?,?)").bind(s,c||null,sender,msg,now()).run();}
async function context(env){const[p,sk,ex,ed,ce,ac,wk,sv,av]=await Promise.all([env.DB.prepare("SELECT * FROM profile WHERE id=1").first(),env.DB.prepare("SELECT name,category FROM skills ORDER BY sort_order").all(),env.DB.prepare("SELECT meta,title,summary,note FROM experience ORDER BY sort_order").all(),env.DB.prepare("SELECT meta,title,summary FROM education ORDER BY sort_order").all(),env.DB.prepare("SELECT title,summary FROM certifications ORDER BY sort_order").all(),env.DB.prepare("SELECT meta,title,summary FROM achievements ORDER BY sort_order").all(),env.DB.prepare("SELECT title,role,organizer,date,description FROM workshops ORDER BY sort_order").all(),env.DB.prepare("SELECT name,description FROM services ORDER BY sort_order").all(),getAvailabilityStatus(env)]);const db=(sv.results||[]).map(x=>x.name+(x.description?`: ${x.description}`:"")),services=[...new Set([...SERVICES,...db])];return{text:`Naveen: ${p?.full_name||"Naveen Shankar D"}\nTitle: ${p?.title||"Network Engineer"}\nLocation: ${p?.location||""}\nBio: ${p?.bio||""}\nEmail: ${p?.email||""}\nServices: ${services.join(", ")}\nSkills: ${(sk.results||[]).map(x=>x.name).join(", ")}\nExperience: ${(ex.results||[]).map(x=>`${x.title}: ${x.summary||""}`).join(" | ")}\nEducation: ${(ed.results||[]).map(x=>`${x.title}: ${x.summary||""}`).join(" | ")}\nCertifications: ${(ce.results||[]).map(x=>`${x.title}: ${x.summary||""}`).join(" | ")}\nAchievements: ${(ac.results||[]).map(x=>`${x.title}: ${x.summary||""}`).join(" | ")}\nWorkshops: ${(wk.results||[]).map(x=>`${x.title}: ${x.description||""}`).join(" | ")}\nLive schedule: ${av.available&&av.shift?`Naveen is available now on ${av.shift.label}, ${av.shift.start_time}-${av.shift.end_time}${av.shift.end_next_day?" next day":""} IST.`:"Naveen is offline/unavailable based on his rotational schedule."}`,profile:p,availability:av};}
function type(v){v=String(v||"").toLowerCase().trim();return v==="online"||v==="offline"?v:null;}
function num(v,max){const n=Number(v);return Number.isFinite(n)&&n>0&&n<=max?n:null;}
function startOf(date,time){const m=String(time||"").match(/(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(!m||!/^(\d{4})-(\d{2})-(\d{2})$/.test(String(date)))return null;let h=+m[1],mi=+(m[2]||0),ap=(m[3]||"").toLowerCase();if(ap==="pm"&&h<12)h+=12;if(ap==="am"&&h===12)h=0;if(h>23||mi>59)return null;const d=String(date).match(/^(\d{4})-(\d{2})-(\d{2})$/);return Date.UTC(+d[1],+d[2]-1,+d[3],h,mi);}
function overlap(a,ah,b,bh){const A=Number(a),B=Number(b),AH=Number(ah||1)*3600000,BH=Number(bh||1)*3600000;return A<B+BH&&B<A+AH;}
async function bookingExtract(env,message,tz){const r=await env.AI.run("@cf/meta/llama-4-scout-17b-16e-instruct",{messages:[{role:"system",content:`Extract booking information. Return ONLY JSON with wants_booking,service,name,email,phone,booking_type,hours,topic,participants,preferred_date,preferred_time,timezone,details. Do not invent. booking_type is online/offline only when explicit. hours and participants are numbers only when explicit. timezone defaults to ${JSON.stringify(tz)}. Services: ${SERVICES.join(", ")}.`},{role:"user",content:message}]});try{const x=JSON.parse(aiText(r).replace(/^```json\s*|\s*```$/g,""));return x.wants_booking?x:null;}catch{return null;}}
async function draft(env,session,d,tz){const old=await env.DB.prepare("SELECT * FROM sana_bookings WHERE session_id=? AND status='draft' ORDER BY id DESC LIMIT 1").bind(session).first();const m={service:d.service||old?.service||null,name:d.name||old?.name||null,email:d.email||old?.email||null,phone:d.phone||old?.phone||null,booking_type:type(d.booking_type||old?.booking_type),hours:num(d.hours||old?.hours,24),topic:d.topic||old?.topic||null,participants:num(d.participants||old?.participants,1000),preferred_date:d.preferred_date||old?.preferred_date||null,preferred_time:d.preferred_time||old?.preferred_time||null,timezone:d.timezone||old?.timezone||tz,details:d.details||old?.details_json||null},ts=now();if(old){await env.DB.prepare("UPDATE sana_bookings SET service=?,name=?,email=?,phone=?,booking_type=?,hours=?,topic=?,participants=?,preferred_date=?,preferred_time=?,timezone=?,details_json=?,updated_at=? WHERE id=?").bind(m.service,m.name,m.email,m.phone,m.booking_type,m.hours,m.topic,m.participants,m.preferred_date,m.preferred_time,m.timezone,m.details,ts,old.id).run();return{...m,id:old.id};}const r=await env.DB.prepare("INSERT INTO sana_bookings(session_id,service,name,email,phone,booking_type,hours,topic,participants,preferred_date,preferred_time,timezone,details_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?)").bind(session,m.service,m.name,m.email,m.phone,m.booking_type,m.hours,m.topic,m.participants,m.preferred_date,m.preferred_time,m.timezone,m.details,ts,ts).run();return{...m,id:r.meta.last_row_id};}
async function conflict(env,b){const s=startOf(b.preferred_date,b.preferred_time);if(!s)return false;const rows=await env.DB.prepare("SELECT id,preferred_date,preferred_time,hours FROM sana_bookings WHERE id!=? AND status IN('new','confirmed','pending') AND preferred_date=? AND booking_type=?").bind(b.id,b.preferred_date,b.booking_type).all();return(rows.results||[]).some(x=>{const o=startOf(x.preferred_date,x.preferred_time);return o&&overlap(s,b.hours,o,x.hours);});}
const missingLabels={service:"the service you'd like",name:"your name",email:"your email",phone:"your phone number",booking_type:"whether you'd like it online or offline",hours:"how many hours you need",topic:"the topic",participants:"the number of participants",preferred_date:"your preferred date",preferred_time:"your preferred time"};
async function chat(request,env){if(!env.AI)return json(request,{error:"Sana isn't configured yet"},400);const body=await request.json().catch(()=>({})),message=typeof body.message==="string"?body.message.trim():"";if(!message||message.length>1000)return json(request,{error:"Please send a message up to 1000 characters."},400);const session=await ensureSession(env,request),tz=timezoneFromRequest(request),local=partsForTimezone(tz),india=partsForTimezone("Asia/Kolkata"),country=request.headers.get("CF-IPCountry")||"IN",c=await context(env),hist=await env.DB.prepare("SELECT sender,message FROM sana_messages WHERE session_id=? AND conversation_id IS NULL ORDER BY id DESC LIMIT 10").bind(session).all();const history=(hist.results||[]).reverse().map(x=>({role:x.sender==="visitor"?"user":"assistant",content:x.message}));await saveMessage(env,session,null,"visitor",message);
if(/\b(sex|sexual|nude|nudes|nudity|porn|pornography|xxx|erotic|horny|blowjob|handjob|masturbat|fuck|dick|pussy|boobs|breasts|anal|onlyfans)\b/i.test(message)){const reply=`${dayGreeting(local.hour)}! 😊 I'm happy to chat with you, but I keep things respectful and I can't help with sexual or nude content. We can talk about Naveen, his work, services, learning, careers, or something fun instead. 💙`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"blocked_content"});}
const b=await bookingExtract(env,message,tz).catch(()=>null);if(b){const d=await draft(env,session,b,tz),missing=Object.keys(missingLabels).filter(k=>d[k]===null||d[k]===undefined||d[k]==="");if(missing.length){const indiaNote=country!=="IN"?` It's ${dayGreeting(india.hour).toLowerCase()} in India right now.`:"";const reply=`${dayGreeting(local.hour)}! 😊 I can arrange that for you.${indiaNote} Could you share ${missingLabels[missing[0]]}?`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_collecting",booking_fields:missing,booking_id:d.id});}if(await conflict(env,d)){const reply=`${dayGreeting(local.hour)}! 😊 That slot is already requested for another ${d.booking_type} booking. Please give me another date or time and I'll check it.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_slot_conflict",booking_id:d.id});}await env.DB.prepare("UPDATE sana_bookings SET status='new',updated_at=? WHERE id=?").bind(now(),d.id).run();const reply=`${dayGreeting(local.hour)}! 😊 Perfect — I've recorded your ${d.service} request for ${d.preferred_date} at ${d.preferred_time} (${d.timezone}), ${d.booking_type}, ${d.hours} hour(s), ${d.participants} participant(s). Your request ID is NS-${d.id}. Naveen will review it and email you about confirmation and pricing.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"booking_created",booking_id:d.id,tracking_id:`NS-${d.id}`});}
if(/\b(live|talk|connect|speak|call|chat with naveen|talk to naveen|connect me)\b/i.test(message)){const p=await env.DB.prepare("SELECT * FROM sana_presence WHERE id=1").first(),online=!!p&&Number(p.online)===1&&now()-Number(p.last_seen_at||0)<=ONLINE_WINDOW_MS;if(!online){const reply=`${dayGreeting(local.hour)}! 😊 Naveen is offline right now. I can leave him a message, or you can come back when he's online.`;await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:"naveen_offline"});}const expires=now()+CONNECT_WINDOW_MS,conversationId=crypto.randomUUID();await env.DB.prepare("INSERT INTO sana_connect_requests(session_id,status,conversation_id,created_at,expires_at,updated_at) VALUES(?,'pending',?,?,?,?,?)".replace("VALUES(?,'pending',?,?,?,?,?)","VALUES(?, 'pending', ?, ?, ?, ?)" )).bind(session,conversationId,now(),expires,now()).run();const reply=`${dayGreeting(local.hour)}! 😊 Naveen is online. I've sent him a connection request and I'll keep it open for about 3 minutes.`;await saveMessage(env,session,conversationId,"sana",reply);return json(request,{reply,action:"connect_requested",conversation_id:conversationId,expires_at:expires});}
const price=/\b(price|pricing|cost|fee|fees|how much|charge|charges)\b/i.test(message),indiaNote=country!=="IN"?` It's ${dayGreeting(india.hour).toLowerCase()} in India right now.`:"",system=`You are Sana, Naveen Shankar D's personal AI assistant. Never call yourself a portfolio assistant. Introduce yourself naturally only when needed; do not repeat your identity in every reply. Be warm, playful, loving, friendly and diplomatic, with light human-like emotion, but never claim to be human. React warmly to compliments and affection without creating a false human relationship. Never engage in sexual, nude, erotic or explicit content. Answer simple time/date questions using the visitor timezone. ${indiaNote} If asked for price, say Naveen will review the request and email them; never invent a price. If asked to book or connect, the server handles that flow. Keep replies 1-4 short sentences.\n\n${c.text}`;try{const r=await env.AI.run("@cf/meta/llama-4-scout-17b-16e-instruct",{messages:[{role:"system",content:system},...history,{role:"user",content:message}]});const reply=aiText(r);if(!reply)return json(request,{error:"No response generated"},502);await saveMessage(env,session,null,"sana",reply);return json(request,{reply,action:price?"price_info":"chat",local_time:local.text,india_time:india.text,timezone,country});}catch(e){return json(request,{error:"Chat request failed",detail:String(e)},500);}}
async function adminAuth(request,env){const a=request.headers.get("Authorization")||"",t=a.startsWith("Bearer ")?a.slice(7):null;return t?verifySessionToken(env.SESSION_SECRET,t):null;}
async function presence(request,env){const a=await adminAuth(request,env);if(!a)return json(request,{error:"Unauthorized"},401);const b=await request.json().catch(()=>({})),online=!!b.online,u=a.username||a.email||"admin";await env.DB.prepare("INSERT INTO sana_presence(id,online,last_seen_at,admin_username,updated_at) VALUES(1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET online=excluded.online,last_seen_at=excluded.last_seen_at,admin_username=excluded.admin_username,updated_at=excluded.updated_at").bind(online?1:0,now(),u,now()).run();return json(request,{online,last_seen_at:now()});}
async function adminRequests(request,env){const a=await adminAuth(request,env);if(!a)return json(request,{error:"Unauthorized"},401);if(request.method==="GET"){const r=await env.DB.prepare("SELECT * FROM sana_connect_requests WHERE status='pending' AND expires_at>? ORDER BY created_at DESC LIMIT 50").bind(now()).all();return json(request,{requests:r.results||[]});}const b=await request.json().catch(()=>({})),id=Number(b.id),status=["accepted","declined","expired"].includes(b.status)?b.status:null;if(!id||!status)return json(request,{error:"id and valid status required"},400);await env.DB.prepare("UPDATE sana_connect_requests SET status=?,updated_at=? WHERE id=?").bind(status,now(),id).run();return json(request,{ok:true});}
async function adminBookings(request,env){const a=await adminAuth(request,env);if(!a)return json(request,{error:"Unauthorized"},401);if(request.method==="GET"){const r=await env.DB.prepare("SELECT * FROM sana_bookings ORDER BY created_at DESC LIMIT 100").all();return json(request,{bookings:r.results||[]});}const b=await request.json().catch(()=>({})),id=Number(b.id);if(!id)return json(request,{error:"id required"},400);const fields=[],values=[],statuses=["draft","new","pending","confirmed","declined","completed","cancelled"];if(statuses.includes(b.status)){fields.push("status=?");values.push(b.status);}if(Object.prototype.hasOwnProperty.call(b,"price")){fields.push("price=?");values.push(b.price===""||b.price===null?null:Number(b.price));}if(!fields.length)return json(request,{error:"No valid fields"},400);values.push(now(),id);await env.DB.prepare(`UPDATE sana_bookings SET ${fields.join(",")},updated_at=? WHERE id=?`).bind(...values).run();return json(request,{ok:true});}
export default{async fetch(request,env,ctx){if(request.method==="OPTIONS")return existingWorker.fetch(request,env,ctx);const p=new URL(request.url).pathname;if(p==="/public/chat"&&request.method==="POST")return chat(request,env);if(p==="/admin/sana/presence"&&request.method==="POST")return presence(request,env);if(p==="/admin/sana/requests"&&(request.method==="GET"||request.method==="POST"))return adminRequests(request,env);if(p==="/admin/sana/bookings"&&(request.method==="GET"||request.method==="POST"))return adminBookings(request,env);return existingWorker.fetch(request,env,ctx);}};
